const cardData = [
  {
    id: "1",
    address: "Property",
    neighborhood: "This is Property.",
    squarefeet: "13",
    parking: "Yes",
    publicTranspo: "Yes",
    price: "100",
    type: "Workspace",
    capacity: "This is Workspace.",
    smoking: "NO",
    available: "Yes",
    term: "Yes",
  },
  {
    id: "2",
    address: "Property",
    neighborhood: "This is Property.",
    squarefeet: "13",
    parking: "Yes",
    publicTranspo: "Yes",
    price: "100",
    type: "Workspace",
    capacity: "This is Workspace.",
    smoking: "NO",
    available: "Yes",
    term: "Yes",
  },
  {
    id: "3",
    address: "Property",
    neighborhood: "This is Property.",
    squarefeet: "13",
    parking: "Yes",
    publicTranspo: "Yes",
    price: "100",
    type: "Workspace",
    capacity: "This is Workspace.",
    smoking: "NO",
    available: "Yes",
    term: "Yes",
  },
  {
    id: "4",
    address: "Property",
    neighborhood: "This is Property.",
    squarefeet: "13",
    parking: "Yes",
    publicTranspo: "Yes",
    price: "100",
    type: "Workspace",
    capacity: "This is Workspace.",
    smoking: "NO",
    available: "Yes",
    term: "Yes",
  },
  {
    id: "5",
    address: "Property",
    neighborhood: "This is Property.",
    squarefeet: "13",
    parking: "Yes",
    publicTranspo: "Yes",
    price: "100",
    type: "Workspace",
    capacity: "This is Workspace.",
    smoking: "NO",
    available: "Yes",
    term: "Yes",
  },
  {
    id: "6",
    address: "Property",
    neighborhood: "This is Property.",
    squarefeet: "13",
    parking: "Yes",
    publicTranspo: "Yes",
    price: "100",
    type: "Workspace",
    capacity: "This is Workspace.",
    smoking: "NO",
    available: "Yes",
    term: "Yes",
  },
];

module.exports = cardData;
