const cardData = [
  {
    id: "1",
    address: "John",
    neighborhood: "This is John.",
    squarefeet: "13",
    parking: "Yes",
    publicTranspo: "Yes",
    price: "100",
  },
  {
    id: "2",
    address: "John",
    neighborhood: "This is John.",
    squarefeet: "13",
    parking: "Yes",
    publicTranspo: "Yes",
    price: "100",
  },
  {
    id: "3",
    address: "John",
    neighborhood: "This is John.",
    squarefeet: "13",
    parking: "Yes",
    publicTranspo: "Yes",
    price: "100",
  },
  {
    id: "4",
    address: "John",
    neighborhood: "This is John.",
    squarefeet: "13",
    parking: "Yes",
    publicTranspo: "Yes",
    price: "100",
  },
  {
    id: "5",
    address: "John",
    neighborhood: "This is John.",
    squarefeet: "13",
    parking: "Yes",
    publicTranspo: "Yes",
    price: "100",
  },
  {
    id: "6",
    address: "John",
    neighborhood: "This is John.",
    squarefeet: "13",
    parking: "Yes",
    publicTranspo: "Yes",
    price: "100",
  },
];
module.exports = cardData;
